services:
  - docker

install:
  - docker build -t ddiez/mrbayes .

script:
  - docker run ddiez/mrbayes

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push ddiez/mrbayes;
    fi
